### ISSUE TITLE
Minor Request: Last Seen Date/Time

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1277]
This is very minor so it certainly isn't a priority but right now, offline agents show the beginning of the last block of time they were online (e.g. if an agent was connected from noon to 4 PM yesterday, the last seen time shows noon instead of 4 PM). Updating this to use the end of that time would make that stat more useful.

**Comment by Ylianst** [comment]
Thanks for the report. Just checked in the fix for this. will be in v0.5.20 when it's next published.

**Comment by Ylianst** [comment]
MeshCentral v0.5.20 is published. Should fix this.

**Comment by PetieM** [comment]
Confirming that v0.5.20 does fix this after the next time an agent checks in (so agents that were already offline prior to this update still show the old value which makes sense).

**Comment by Ylianst** [comment]
Correct, I can't fix the old values in the database. Should update correctly from now on.
