### ISSUE TITLE
Router: Quick mapping buttons grayed out?

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#1438]
Not sure when this started. Mesh Router related.
Mesh: 0.5.49

All the "RDP", "HTTP", "SSH" quick buttons are grayed out. However, you can do a map manually with no issue.

![image](https://user-images.githubusercontent.com/779947/83435756-646d5c80-a402-11ea-85d4-ae3923a089c4.png)
![image](https://user-images.githubusercontent.com/779947/83435846-836bee80-a402-11ea-929a-f5ceb12ebb2c.png)

**Comment by vitko-bg** [comment]
@Ylianst - possibly is related to last post in #1309 

@MordyT - I have the same issue, not sure what your setup is.

**Comment by MordyT** [comment]
@vitko-bg Maybe. I have (in each domain) a user in the managealldevicegroups that is local to mesh and in the primary domain I have both a local user and a SSO user there.

No users (admins, local, SSO, etc) have the quicklinks working.

**Comment by Ylianst** [comment]
The buttons are normally grayed out when your account does not have "Remote Control" rights to the devices. That is the permission required to perform traffic forwarding. If you have some detail as to how the permissions are granted (thru a user group?) I will debug this.

**Comment by MordyT** [comment]
The account is a member of a user group. That user group is a full administrator on a mesh device group.

If I manually add a specific user to a specific device as Remote Control, the button lights up right away.

**Comment by Ylianst** [comment]
Excellent, I see the same problem now. Working on it.

**Comment by Ylianst** [comment]
Ok, fixed it. Will be in the next version of MeshCentral, however since the problem is with the MeshCentral Router only, you can get the [latest version here](info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe).

**Comment by petervanv** [comment]
@Ylianst your link to meschcentral router is incorrect, this one is working http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe

**Comment by Ylianst** [comment]
Thanks @peteranv, fixed my link.

**Comment by MordyT** [comment]
New router does fix the buttons grayed out. However, I'm facing an issue on some PCs (even with old router) where the router can launch normally, but when launched from the webapp we get this error. Only on some machines - is there a dependency missing on those machines?

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at MeshCentralRouter.MainForm.nextButton1_Click(Object sender, EventArgs e)
   at MeshCentralRouter.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MeshCentralRouter
    Assembly Version: 1.0.7458.922
    Win32 Version: 1.0.7458.922
    CodeBase: file:///C:/Program%20Files/Mesh/Router.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`

**Comment by Ylianst** [comment]
I am pretty sure I found the problem and fixed it, you can try the latest [MeshCentral Router here](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe). Let me know if it works.

**Comment by MordyT** [comment]
@Ylianst 
Progress. Login works, but clicking the RDP icon crashes it with a similar message (Invalid URI: The hostname could not be parsed).

Strange how it works well on some of our PCs and others have this error.

**Comment by Ylianst** [comment]
One more version of [MeshCentral Router here](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe). This one should fix the Invalid URI exception, let me know if it works.

**Comment by MordyT** [comment]
Tried the latest version, I'm still getting this when clicking the RDP button:
![image](https://user-images.githubusercontent.com/779947/84069203-cf350f80-a98f-11ea-82a9-7ea2c584d95f.png)
I have another user who reported getting this when trying any RDP from router:
![image](https://user-images.githubusercontent.com/779947/84069243-df4cef00-a98f-11ea-8ea5-83bc88ad07fc.png)

**Comment by Ylianst** [comment]
HA!! Ok, I see the problem now. Thanks for posting the details, will work on this.

**Comment by Ylianst** [comment]
I just did a quick, end of day fix... new [MeshCentral Router is here](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe). Let me know if it works now.

**Comment by MordyT** [comment]
@Ylianst My team is telling me that the newest version has fixed all reported issues. I'll close this for now and let you know if the issue returns.

THANK YOU!
