### ISSUE TITLE
Link in account invitation sent by e-mail

### ISSUE THREAD

**Issue by rrech** [Ylianst/MeshCentral#2089]
Hi guys. The link sent by e-mail does not consider LoginKey configuration.

**Comment by Ylianst** [comment]
I fixed this and made other email improvements, will be in MeshCentral v0.7.29.

**Comment by rrech** [comment]
> I fixed this and made other email improvements, will be in MeshCentral v0.7.29.

Tks, Ylian!

**Comment by rrech** [comment]
Ylian, updated to 0.7.31 and the link in e-mail sent when creating a new account still not contains the LoginKey in the URL. Am I doing something wrong or something?

**Comment by Ylianst** [comment]
One thing to check, if you go in your "meshcentral-data" folder and have a "email templates" folder (I forget the exact name) that has a set of email template files in it, rename that folder and restart your server. That should fix it. 

The problem may be that you have a set of older email templates in that folder that does not include the login key. If you rename the folder, it should take default templates that add the key.

This said, I will take a look again.

**Comment by rrech** [comment]
Hi Ylian, sorry for the delay in answering you. I did not find any folder with any similar name in meshcentral-data.
