### ISSUE TITLE
Debian 9, 32 bit, mesh agent disconnects, CPU utilization 100%

### ISSUE THREAD

**Issue by nlyaple** [Ylianst/MeshCentral#2147]
On our x86 Debian 9, 32 bit based systems we are seeing random (7 out of 50) Mesh Agents losing connection and the CPU utilization going to 100% on one core.  The version info is:

```
{
  "openssl": "1.1.1g",
  "duktape": "v2.3.0",
  "meshAgent": "2020-09-10T17:49:26.000Z"
}
```

We are using the last stable server version 0.6.70.
We are able to recover by rebooting the system.

**Comment by Ylianst** [comment]
I am pretty sure this problem was solved already and later versions of MeshCentral. Bryan solved the 100% CPU issue a while back. I am currently testing MeshCentral v0.7.41 on MeshCentral.com and will likely move the "stable" version to v0.7.41 at the end of the week.

**Comment by nlyaple** [comment]
Hi,
     Any update on updating the stable version?
Thanks,
Nelson

**Comment by nlyaple** [comment]
Hi,
      I just checked and see the Stable Version is still 0.6.70.  We are still seeing these issues,  should we just upgrade to the Latest Version 0.7.84?
Thanks,
Nelson

**Comment by Ylianst** [comment]
You can can update to the latest version. I am been using the latest v0.7.8x versions on [MeshCentral.com](https://meshcentral.com) for quite a while and the new agents are much more stable. Of course, always do industry best practices when updating any software. Perform a off-site backup of the MeshCentral files and database regularly. Make sure to include "meshcentral-data" folder, that one is critical. Make sure you can restore it and ideally, you should test on a pre-production server first to make sure your specific usages and configuration work before updating a production server.

This said, I am very happy with the new set of agents for Windows/Linux.

Lastly, if you are using any MeshCentral plug-ins, let us know. I don't test plug-in's at all.

Hope that helps,
Ylian
