### ISSUE TITLE
Messenger displays "%20" instead of "space" plus 2 more ...

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#2214]
Actually it is a couple of issues, sorry to post them in one issue, but all of them, are Messenger related:

1. When starting a chat with remote PC, if in PC name are spaces, it displays %20 on Operator screen:

![Capture1](https://user-images.githubusercontent.com/59362521/105837343-7e2d6680-5fc6-11eb-849c-8581903a2afb.PNG)

2. Also - I decided to improvise and I tried a MeshMessenger personalization, but tried to add a User name parameter in config.json, looks like it is not implemented and that why it is not working. However, may I request this option to work please:

![Capture](https://user-images.githubusercontent.com/59362521/105837507-b46ae600-5fc6-11eb-8b6b-6caff7dcd93b.PNG)

3. Even after Messenger is personalized, it is still showing in Windows Toast notification as Mesh Messenger - on both sides operator and remote PC.

![Capture2](https://user-images.githubusercontent.com/59362521/105838092-8afe8a00-5fc7-11eb-8cde-be62fde7c271.PNG)
![Capture3](https://user-images.githubusercontent.com/59362521/105838101-8df97a80-5fc7-11eb-93d8-debf07e9c3cd.PNG)

Running on latest MC2 0.7.53

**Comment by Ylianst** [comment]
Working on this one now.

**Comment by Ylianst** [comment]
Ok, it's check it and will be in MeshCentral v0.7.54. You can use {0} to show the remote user's real name or userid if no real name was set. You can use {1} to show the user id. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/105897040-7cff3800-5fcc-11eb-9517-584cc5d6afb1.png)

**Comment by vitko-bg** [comment]
Thanks a lot! Will test all reported issues + 1 enhancement :) once new version released and will post back. Thanks again!

**Comment by vitko-bg** [comment]
THANKS!!!! All work as expected in latest 0.7.54!

**Comment by vitko-bg** [comment]
Unfortunately in config.json non of the parameters {0} or {1} getting the real name
Tried both
"meshMessengerTitle": "Chat with operator \"{1}\".",
and
"meshMessengerTitle": "Chat with operator \"{0}\".",
restarted the server, but on messenger displays the "User Identifier" - the only difference is with {1} on messenger user identifier displays with capital letter, i.e. "**John**", with {0} displays as "**john**"

**Comment by Ylianst** [comment]
Interesting. I will take a look at that. Does the real name start with "John XXXXX"? It may be the real name is not displayed passed the space. I will check.

**Comment by Ylianst** [comment]
Oh. I see. Your right, my fault... fixing this now.

**Comment by Ylianst** [comment]
Fixed it. It will be in v0.7.55 when it's next published. Thanks for reporting this. Should not work as expected.

![image](https://user-images.githubusercontent.com/1319013/106068143-f3776500-60b4-11eb-8eec-d51c3c47ea1f.png)

**Comment by LPJon** [comment]
> 
> 
> Fixed it. It will be in v0.7.55 when it's next published. Thanks for reporting this. Should not work as expected.
> 
> ![image](https://user-images.githubusercontent.com/1319013/106068143-f3776500-60b4-11eb-8eec-d51c3c47ea1f.png)

@Ylianst  I'm still seeing an email address instead of the real name when using `{0}` in the config.json. I'm using v0.7.55

**Comment by LPJon** [comment]
@Ylianst I should note that my User Identifier is an email address, but it doesn't matter which switch I use `{0}` or `{1}` still produces and email address. There is an actual name in the "Real Name" space.

**Comment by LPJon** [comment]
@Ylianst Is this the proper way to implement this feature?
`"meshMessengerTitle": "Messenger chat with {0}",`

**Comment by LPJon** [comment]
@Ylianst The upgrade to v0.7.55 didn't upgrade the `webserver.js` file on my server with your new changes for this. After manually applying them they worked. Just thought you should know. Is it possible you meant v0.7.56?

> 
> 
> Fixed it. It will be in v0.7.55 when it's next published. Thanks for reporting this. Should not work as expected.
> 
> ![image](https://user-images.githubusercontent.com/1319013/106068143-f3776500-60b4-11eb-8eec-d51c3c47ea1f.png)

**Comment by Ylianst** [comment]
Arg. Your right, I meant v0.7.56. Apologies for that. Yes, it would be fixed in the next version, however it seems your the first one that I know off that is applying GitHub changes ahead of release! Nicely done.

**Comment by vitko-bg** [comment]
0.7.56 - Displaying the "Real name" information. Confirmed working!
Thanks!
