### ISSUE TITLE
MeshCentralAssistant

### ISSUE THREAD

**Issue by TiaPcom** [Ylianst/MeshCentral#2260]
Hi, how does it work the tray icon?
We can't open requests (if I click on Request Help nothing happens)
Is it normal?

**Comment by vitko-bg** [comment]
Can you see that Agent is installed? Or it shows on Assistant "Agent not installed"
![image](https://user-images.githubusercontent.com/59362521/107040122-b3039f80-67b6-11eb-9604-f79b7a82e9f9.png)

If you are using agent customization - it won't work, there is a request open in regards to this case.

Otherwise, if you click on request help it should work the way as in link - for me all is fine and all is working as expected:

[https://github.com/Ylianst/MeshCentralAssistant/issues/3#issuecomment-735042618]

**Comment by Ylianst** [comment]
Arg. I have to put some more time on MeshCentral Assistant. It the agent is detected as not installed, the request help button should not be enabled in the first place. I have to figure out something for agent branding because you can have many different branded agents on the same machine and MeshCentral Assistant needs to be itself branded and look for it's corresponding agent.

**Comment by TiaPcom** [comment]
Hi Ylianst, no the agent is not branded.
Assistant detects agent correctly but no action is taken when I click on "Request Help".
![image](https://user-images.githubusercontent.com/77863847/107117017-93807b80-6877-11eb-986b-053b772a2a67.png)

**Comment by TiaPcom** [comment]
I also notice that Request Help is grayed
![image](https://user-images.githubusercontent.com/77863847/107117136-67b1c580-6878-11eb-8bfd-0df03bf4641f.png)

**Comment by vitko-bg** [comment]
@TiaPcom what MC2 version you are running and what agent version?

**Comment by TiaPcom** [comment]
MC2 version 0.7.63
Agent file version 0.2.1.3

**Comment by VINISHVV** [comment]
@Ylianst 
Pls fix this issue.

**Comment by Mfinadmin** [comment]
Assistant detects agent correctly,  but request help button is inactive.

Meshcentral  version 0.7.88

**Comment by VINISHVV** [comment]
@Ylianst 

Can you priorities this.

**Comment by VINISHVV** [comment]
This  issue  fixed in v0.8.16 as per #2518 , But need to download New Assistant version is [available here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralAssistant.exe).

**Comment by VINISHVV** [comment]
Hi, 
Since it's fixed. Can you check it once and close this issue.

**Comment by TiaPcom** [comment]
Hi, I've downloaded the last version of Assistant but still not working for me.
How it can be?

**Comment by VINISHVV** [comment]
You need to upgrade the meshcentral version to latest one.
