### ISSUE TITLE
Intel ME Invalid Credentials 

### ISSUE THREAD

**Issue by SurrounDTech** [Ylianst/MeshCentral#2421]
Hi all,

Environment:
Server OS: Windows Server 2019
MeshCentral: 0.7.72
NodeJS: 14.15.1
Desktop: Windows 10 Pro & Windows 10 Enterprise LTSC 2019 

Not sure if anyone else has experienced this, I have two device both Windows 10 Pro which had both the Mesh Agent and Intel AMT CIRA configured and working (in band and out of band connections worked great). The device group was set as Fully Automatic
![image](https://user-images.githubusercontent.com/65645186/112420272-af34d800-8d78-11eb-8dab-70465318a85b.png)
I reimaged these devices to Windows 10 LTSC 2019 and reinstalled the Mesh Agent. When the mesh agent reinstalled it created a new device in the device group (which was expected as the previous agent db had been blown away with the reimage) but now both devices are asking for credentials in Intel ME and are no longer showing TLS. 
![image](https://user-images.githubusercontent.com/65645186/112420642-4bf77580-8d79-11eb-8e72-db281a03a79c.png)
In the details tab it shows as that the Admin credentials are known and TLS is not setup, but another device I have in another group is using TLS.
![image](https://user-images.githubusercontent.com/65645186/112420806-937e0180-8d79-11eb-96be-34e03de37865.png)
On the IntelAMT tab when connecting I receive the Set New Credentials error and upon resetting them I receive the same error and the same when entering in the new credentials into the General tab (Intel ME).
![image](https://user-images.githubusercontent.com/65645186/112420934-d3dd7f80-8d79-11eb-8e94-79d20d1b730a.png)
In the console tab of the devices I checked the amtevents and received the following. And when running amtconfig nothing happens.
![image](https://user-images.githubusercontent.com/65645186/112423102-c1654500-8d7d-11eb-8bcc-7b1d4696fa25.png)
I had a look into the amtactivation.log and have tried using the old password from when the device activated without luck, I did not see any entries for the device reactivating in the log (not sure if there should have been). I'm now at the point where I am think I will have to deactivate and reactivate the AMT setting using the setup.bin file on a USB. Ultimately I would like to be able to remotely rebuild a device and still be able to use Out of Band management to get to the BIOS etc. without having to run the setup.bin file again.

Is there anything I could be doing wrong / not understanding or does reimaging a device and reinstalling the agent cause issues with Admin Credentials. Please let me know if anymore info is needed.

Thanks

**Comment by Ylianst** [comment]
This will required a bit more time for me to answer, this is a long topic... but you did point out that the "Details" tab was showing an incorrect value, I fixed that last night and the current version of MeshCentral will show the correct value.

![image](https://user-images.githubusercontent.com/1319013/112577997-b24cba00-8db2-11eb-8167-a69b65a7d961.png)

**Comment by Ylianst** [comment]
have you tried clicking on "Invalid Credentials" and setting the correct password?

![image](https://user-images.githubusercontent.com/1319013/112675610-9eda3700-8e24-11eb-8147-c8e5242dd6b3.png)

It should switch to "Trying Credentials" and if it works, it will switch to being ok. After that, everything should work.

By the way, the fully automatic mode will setup randomized passwords to Intel AMT. If you want to use the same password for all Intel AMT devices (which is less secure) you can switch your Intel AMT policy to this:

![image](https://user-images.githubusercontent.com/1319013/112675838-e5c82c80-8e24-11eb-9d4a-749e11e619e9.png)

Then, in the domain section of the config.json, you can add this:

```
      "AmtManager": {
        "AdminAccounts": [
          {
            "user": "admin",
            "pass": "xxxxxxxxxxxxxxxxxxxx"
          }
        ]
      },
```

The "AdminAccounts" section indicates a list of passwords to try when seeing a new Intel AMT device. If you put one or more passwords in that section, it will try them all to see if one works. So, if you don't need the security of randomized passwords, this policy setup will allow you to recover all your devices very quickly.

Another thing I can do in the future is extract all the passwords from the amtactivation.log file and try that. I would get the device UUID, user and password and try that when I see a device matching the UUID.

**Comment by SurrounDTech** [comment]
Thanks for the reply @Ylianst 

I ended up going back through the amtactivation.log and trying the passwords from there again and have got both devices to connect again via AMT. One is still showing as Invalid Credentials but it is working fine. I think I need to update to the latest MeshCentral version to see if that fixes the Invalid Credentials message.
