### ISSUE TITLE
Mesh Assistant - more user friendly

### ISSUE THREAD

**Issue by energywave** [Ylianst/MeshCentral#2715]
We're using MeshCentral to assist remote customers by working on their desktop. Until now we used the Agent but let te user do it by using the invitation page is difficult.
Now I've seen the Assistant and it's the missing puzzle piece of this wonderful system.
But I have two problems with it:

1. (I think I'm missing something trivial here...) In the recent blog post about assistant you said it could be used without agent to establish a connection but I cannot use it in that way. I've tested it on a fresh VM and I can see this page 
![image](https://user-images.githubusercontent.com/2051567/120340320-3319bc00-c2f6-11eb-974c-e953d2fe8e22.png) with the "Request help" button disable. If I launch assistant on a PC with the Agent installed then it's working. What I'm missing? The VM is a Win7 but I've also tested with a physical Win10 64bit, same behavior.
2. It would be **so nice** if the Assistant will start **not** in the system tray and with a clear option to start assistant. The principle is to mimic TeamViewer or similar software where you have to direct a user to download the client in the most easy way (and we're ok here, just download the Assistant and put it on the company website) and when the customer launch the exe must have the easiest path to connect. Maybe it's difficult to trust me but many customers don't event know what tray bar is and you have to say "icons at the left of the Windows clock in the bottom right corner of the screen", then you have to explain that tray bar icons are hidding in the "small arrow pointing upside", etc... It's a nightmare. So if the exe will launch the window with the button to connect in the easiest way possible that would be great!

Attached the debug of MeshAssistant

[debug.log](https://github.com/Ylianst/MeshCentral/files/6577080/debug.log)

Thank you in advance as always!

**Comment by Ylianst** [comment]
Hi. For number 1, it should now be fixed. Try the latest version of MeshCentral, should work now. I also noticed from your image that the MeshCentral Assistant UI does not look good on displays with high DPI settings. I still need to fix that. Thanks for posting the debug.log file.

For number 2, yes, absolutely. I have never used TeamViewer but I do want to have another even simpler way to get started with Assistant. I will get something done in this space for sure.

**Comment by energywave** [comment]
Thank you Ylian for your great support!
Unluckily I've tested latest version of MeshCentral (0.8.55) and it still don't works. This time the image in the Assistant get a red glowing just after being open but Request help is still disabled and I don't see the device in MeshCentral.
Here the screenshot
![image](https://user-images.githubusercontent.com/2051567/120620388-3aa7a500-c45d-11eb-87b1-d47c616c0ded.png)
And here the updated debug.log:
[debug.log](https://github.com/Ylianst/MeshCentral/files/6590464/debug.log)

These data are from a Win7 64bit VM test machine but I've also tested on a Win10 64bit physical machine, same behavior.

And about number 2... thank you so much! MeshCentral is so wonderful. I can say that with difficult connections it works even better than TeamViewer... I love it.

If you need some test I'm here.

**Comment by Bobberty** [comment]
Just working with this kit for a bit.  DIscovered that the Assistant defaults to Mesh Agent for the Agent Select.  
It appears a user needs to right click on the Mesh Assistant icon in the system tray, select "Agent Select" and choose "Direct Connect"

Is it possible to default to "Direct Connect" if an agent is not installed?

**Comment by Ylianst** [comment]
FYI. Next version of MeshCentral Assistant will support high DPI displays correctly. This is a screenshot at 150% font size, now shows up centered correctly.

![image](https://user-images.githubusercontent.com/1319013/120714417-042b5380-c478-11eb-9024-eccd841761d8.png)

**Comment by Ylianst** [comment]
@Bobberty MeshCentral Assistant will default to the built-in agent, but will also remember the last agent you selected the next time you run it. I will change it to default to the built-in all the time if it's setup.

**Comment by Ylianst** [comment]
@energywave I think you are sill using an older version of MeshCentral Assistant, but to make sure, the debug.log in the next version will add the version number to the log:

```
14:40:PM.4900: ***** Starting MeshCentral Assistant *****
14:40:PM.4920: Version 0.1.7824.26423                                       <-----------------
14:40:PM.4920: Checking for embedded MSH file
14:40:PM.5350: Set TLS 1.2
14:40:PM.5370: InitializeComponent()
14:40:PM.6700: Check for built-in agent
```

**Comment by Bobberty** [comment]
I might be missing something....  In my lab, if I download Assistant, it appears to default to the Mesh Agent.  I have to select Direct Connect for this to work on a system without an agent installed.  I recognize that being in a lab, there could be registry settings and other apps interfering with the setting. 

To be clear, is this tool supposed to default to "Direct Connect"?  Is this considered the "Internal Agent"?

As a side note, I really appreciate this toolset.  It really scratches an itchy spot for supporting systems.

**Comment by Ylianst** [comment]
I am coming out with an improved MeshCentral Assistant later today in v0.8.56. Hopefully it will fix a lot of issues.

**Comment by Ylianst** [comment]
MeshCentral v0.8.56 is out. Feedback appreciated.

**Comment by Ylianst** [comment]
Oh my gosh. Thank you. Do take note of any feedback.

**Comment by tranbert** [comment]
Customization ok.... 

Just updated my website with a smooth and zen "how to" :  download click and voilà... (I'll take care oft the rest.)

https://i.imgur.com/iD8yqcx.png

**Comment by Ylianst** [comment]
Très bien!

**Comment by energywave** [comment]
Hello, I've tested latest version 0.8.57.
I have different behaviors on different machines. But it's promising!
On a physical updated Win10 64bit all is working right! I've tested "Application, connect on user request". It's working! Good work!
On the VM with Win7 SP1 64bit it's working and connecting, I can connect to desktop, I get some updated, for example on mouse hovering elements I see them updating, but if I change a big portion of the screen like moving a window or opening the start menu the updates of the screen stop working.
The mouse events are still sent as clicks and movement are working but without seeing what's happening on the remote screen.
Even the refresh button that you added on my past request (thanks!!!) is not doing anything.
If that could be of some help the screen of that Win7 is configured at 150dpi as I'm using it to debug my applications with high dpi settings.
Here the debug.log: 
[debug.log](https://github.com/Ylianst/MeshCentral/files/6609895/debug.log)
(you have to write a function to anonymize the log automatically that's quite a work to do it manually... ;) )

If I can be of help to do some test I'm here.

**Comment by MailYouLater** [comment]
> On the VM with Win7 SP1 64bit it's working and connecting, I can connect to desktop, I get some updates, for example on mouse hovering elements I see them updating, but if I change a big portion of the screen like moving a window or opening the start menu the updates of the screen stop working.
> The mouse events are still sent as clicks and movement are working but without seeing what's happening on the remote screen.
> Even the refresh button that you added on my past request (thanks!!!) is not doing anything.

I have also had this issue, but on a Windows 10 laptop.  The issue occurs either way, but it seemed to be worse for me when I had `desktopMultiplex` enabled.

> If that could be of some help the screen of that Win7 is configured at 150dpi as I'm using it to debug my applications with high dpi settings.

I don't believe I have any high-dpi settings enabled on my laptop, unless using virtual super resolution in AMD Radeon settings counts.  I have that set to make my 1366x768 laptop display act as if it's 1920x1080.

**Comment by Ylianst** [comment]
I will close this issue since the original issue has been solved. For other issues with remove desktop, please open a new issue. Thanks.
