### ISSUE TITLE
MechCentral not update the sessions status

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#2855]
Hi,
I have noticed recently that when start meshcmd relay session or rdp or web-rdp session, looking at meshcentral web devices list shows that blue tag which indicates a running session. But after that session ends, the blue indication at meshcentral web doesn't go away. it stays there for ever (days) unless I restart the server so it goes off. have a look at the screenshot to understand more. Thanks
![session not updated](https://user-images.githubusercontent.com/70715469/124293644-35dc2b00-db9a-11eb-8330-40722083d170.PNG)

**Comment by Ylianst** [comment]
Oh! Thanks for reporting this. Yes, once that icon is stuck, the only way to "resync" would be to drop the agent connection and force that agent to reconnect.

![image](https://user-images.githubusercontent.com/1319013/124303004-c3763700-db16-11eb-98a1-a444ce855397.png)

However, much better that I fix this. If you have exact steps to make this happen, please let me know. I will do some testing and fix ASAP.

**Comment by Ylianst** [comment]
I see the same problem! Working on it.

**Comment by Ylianst** [comment]
Fixed it. This will be in MeshCentral v0.8.71.

**Comment by smartekIT** [comment]
Thanks heaps,
while I got you here, the other day was thinking if one of the users using meshcmd rdp relay and let's say I decided to kick him out and kill his session to that computer (specially sometimes when users forgot to disconnect their rdp session). how i can force his session to close from the GUI at MeshCentral Web Interface?

**Comment by smartekIT** [comment]
By the way, even when computers shuts down they still showing online in the Web Device List !!!!  looks like a major thing. Hope your v0.8.71 fix them all :)

**Comment by Ylianst** [comment]
Your going to have to open separate issues :) On computer shutdown, it should show right away. If you unplug the network, it should take 2 minutes before it shows disconnected. So, if you turn off a computer and after 2 minutes the server still shows online, that is a problem.

There is no way to disconnect another user's session right now. You can open a request for that. One thing you can do is lock a user's account and unlock it. That will log them off and drop all sessions.

**Comment by smartekIT** [comment]
HI, just letting you know that the issue still present. turning off computer or restarting them while still showing online at the device list in MeshCentral Web. it's never been like this before. note i already updated to v0.8.72

**Comment by Ylianst** [comment]
Your providing very little details. When you say "it shows online", what do you mean? What do you see on the screen? If you hit refresh on the browser, does it still show "online"? Does "online" mean the blue session indicator is still shown? Can you provide screen shots? When you turn off the computer, does it still show online after 2 minutes? What database are you using (Built-in NeDB, or MongoDB/MySQL/MariaDB)? What version of NodeJS are you using? - Thanks.

**Comment by smartekIT** [comment]
HI, online means it's not greyed out. no blue tag indication because didn't do any session there but the device is listed in the online devices while it's turned off. i'm talking about a whole day not only 2 minutes after turning off that device.
{
    "dbType": "MongoDB",
    "dbChangeStream": false,
    "nodeVersion": "v14.9.0",
    "meshVersion": "0.8.72",
    "platform": "linux",
    "arch": "x64",
    "pid": 2063,
    "uptime": 31113.564213355,
    "cpuUsage": {
        "user": 124269916,
        "system": 43582605
    },
    "warnings": [],
    "database": "MongoDB",
    "productionMode": true,
}
