### ISSUE TITLE
Errors in Linux terminal after updating agent 0.8.98

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#3000]
There is a problem with TERM and PATH variables when connecting to terminal on Linux servers. Depending on the version and distribution, we get different errors related to the absence of this pre-run environment.
When connecting, we immediately see the error "TERM environment variable not set". Which leads to other consequences. not able to run some commands such as "nano", "asterisk -r" and others.
Terminal responses "bash: asterisk: command not found", "Error opening terminal: unknown." and the like.
Every time you connect, you have to do "export TERM = xterm" and "export PATH = / usr / local / sbin: / usr / local / bin: / usr / sbin: / usr / bin" for this to work.
As we can see, these environment variables are really not there when connecting
[root@pbx meshagent]# env
LS_COLORS=
COLUMNS=198
PWD=/usr/local/mesh_services/meshagent
LANG=en_US.UTF-8
LINES=47
HISTCONTROL=ignoreboth
SHLVL=1
VISUAL=nano
LESSOPEN=||/usr/bin/lesspipe.sh %s
_=/usr/bin/env

**Comment by krayon007** [comment]
By any chance, if you right click on connect, and select login shell, does it work correctly?

Also, which Linux distribution and version are you running?

**Comment by AntonAndreevichMoroz** [comment]
Shell login works fine. We noticed this on different servers. Here is a Debian 10 example
![image](https://user-images.githubusercontent.com/51225180/128589431-715afc48-3259-4f4e-860d-5d244ea5ff17.png)

On CentOS 7, I can't check the shell login, for some reason it doesn't accept root login, says "Login incorrect" although the password is exactly correct, I log in via SSH.

**Comment by rapi3** [comment]
I have the same problem on Ubuntu servers after upgrade MC:
``` alias ls='ls --color=auto';clear
root@AR3600:/usr/local/mesh_services/meshagent#  alias ls='ls --color=auto';clear
TERM environment variable not set.
root@AR3600:/usr/local/mesh_services/meshagent# uname -a
Linux AR3600 4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@AR3600:/usr/local/mesh_services/meshagent# top
TERM environment variable not set.
root@AR3600:/usr/local/mesh_services/meshagent# htop
Error opening terminal: unknown.
root@AR3600:/usr/local/mesh_services/meshagent# nano
Error opening terminal: unknown.
root@AR3600:/usr/local/mesh_services/meshagent# set
BASH=/bin/bash
BASHOPTS=checkwinsize:cmdhist:complete_fullquote:expand_aliases:extquote:force_fignore:histappend:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="4" [1]="4" [2]="20" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
BASH_VERSION='4.4.20(1)-release'
COLUMNS=127
DIRSTACK=()
EUID=0
GROUPS=()
HISTCONTROL=ignoredups:ignorespace
HISTFILE=/root/.bash_history
HISTFILESIZE=2000
HISTSIZE=1000
HOSTNAME=AR3600
HOSTTYPE=x86_64
IFS=$' \t\n'
LESSCLOSE='/usr/bin/lesspipe %s %s'
LESSOPEN='| /usr/bin/lesspipe %s'
LINES=40
LS_COLORS=
MACHTYPE=x86_64-pc-linux-gnu
MAILCHECK=60
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PIPESTATUS=([0]="1")
PPID=13665
PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
PS2='> '
PS4='+ '
PWD=/usr/local/mesh_services/meshagent
SHELL=/bin/bash
SHELLOPTS=braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor
SHLVL=1
TERM=dumb
UID=0
_=nano
root@AR3600:/usr/local/mesh_services/meshagent#

**Comment by fernandogobah** [comment]
+1
I have the same problem all devices linux (Debian, Ubuntu, Raspbian)

TERM environment variable not set.

**Comment by lergolas** [comment]
+1 
-------------
alias ls='ls --color=auto';clear
root@NASOMV:/usr/local/mesh#  alias ls='ls --color=auto';clear
TERM environment variable not set
-------------

In Debian 8 / 9 and Ubuntu 16.04

**Comment by krayon007** [comment]
Ok, I pushed a server side fix for this. The bug is that that the TERM environment variable is not set if an environment block is passed to the child process. This happens because previously environment variables were set in the parent, and inherited by the child, but I fixed that so it is only set in the child. However, the TERM variable was not passed in the env block, it was set in the parent before, so was inherited...  I was able to fix this behavior server side, so that the TERM variable is set in the environment block passed to the child.. I can post back here when the change goes live.

**Comment by Ylianst** [comment]
MeshCentral v0.9.1 was just published with Bryan's fix for this. Let us know if it works.

**Comment by AntonAndreevichMoroz** [comment]
When working through the Terminal, the Term variable appeared. This partially solved the problem, but as I wrote, there is also no PATH variable. Here is the output via the Terminal tab.
![image](https://user-images.githubusercontent.com/51225180/129092369-28e399c7-f4c0-4889-84c7-17650bfda910.png)

And the output when connecting via Web-SSH or Putty
![image](https://user-images.githubusercontent.com/51225180/129092645-33b0f765-cbc4-41e8-bafa-a513643ffee9.png)

**Comment by rapi3** [comment]
+1 missing path, it need:
```
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by krayon007** [comment]
Ok, the primary reason for this difference, is that SSH uses loginshell when connecting the pty. The terminal connect does not, unless you select loginshell. Login shell will load the user profile, which is probably why all those other variables are missing when you just use regular terminal.

I can probably just specify the PATH env from the parent. But beyond that, there isn't really much I can do, as the parent process only has 2 or 3 env variables set... lang and path.

**Comment by krayon007** [comment]
If setting LANG and PATH is sufficient, I can easily do that with another service side change.

**Comment by AntonAndreevichMoroz** [comment]
I think that's enough.  I did not notice any other problems.  Thank you for your quick response.

**Comment by krayon007** [comment]
Ok, I pushed a server side change, to add LANG and PATH. It should get picked up with the next server update.
