### ISSUE TITLE
Assistant Hanging issues

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#3212]
Hi Ylianst,

Sorry for creating duplicate task.

Can you fix the assistant hang issues?

**Comment by Ylianst** [comment]
This morning I was working on this and did find a bug in the websocket compression that could cause a problem. By change chance, are these options present on your servers:

```
    "WsCompression": true,
    "AgentWsCompression": true,
```

If so, can you change them to `false` and see if it fixes the Assistant hang issue?

I am working on a new version of MeshCentral Assistant that uses the Windows built-in web socket code when running on Windows 8 and higher. Because it's completely different code for sending and receiving data, I hope that will fix it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.40 with an updated MeshCentral Assistant that should fix this issue. Let me know if it works.

**Comment by VINISHVV** [comment]
@Ylianst Thanks.

Now we can see little improvements, But the desktop display is still hanging.

**Comment by SPEMoorthy** [comment]
@Ylianst Thanks for this good product. I am new to this product. Just 4 days old. 

For your Info am using v0.9.40 assistant.. but It is hanging... No Inputs are having response... But if I use the agent service the experience is very smooth. Is there any technical difference in agent in service mode and assistant? Is the problem is with Assistant UI or underlaying technologies used in assistant? How can we came out of the hanging issue in assistant? Moreover Assistant's functionalities is much appreciated in product support , customer care support industries. Thanks again for an amazing tool.

Thanks & Regards,
@spemoorthy

**Comment by Ylianst** [comment]
Hi. Can I get confirmation that Assistant still hangs with no compression enabled? Put these two lines and see if Assistant still hangs?

```
    "WsCompression": false,
    "AgentWsCompression": false,
```

Also, make sure you download and try to latest MeshCentral Assistant, not just update the server.

MeshCentral Assistant (Written in C#) is completely different code from MeshAgent (Written in C/JS). So, it's not a surprise they behave completely differently.

The easiest way to fix this issue is to have me replicate the problem. So far, I try different things but still can't get it to hang. I you want to give me a dummy account on your server, please send information to [my contact info here](https://www.meshcommander.com/contact-information). If I can replicate the issue, I am pretty sure I can fix it.

**Comment by SPEMoorthy** [comment]
Dear @Ylianst,

After Changing setting to 
  ` "WsCompression": false,
    "AgentWsCompression": false,`
The assistant still hangs.

**Comment by VINISHVV** [comment]
@Ylianst 

I have mailed the dummy account credentials to your mail-id.

**Comment by Ylianst** [comment]
OK! Thanks to @VINISHVV  I have just published MeshCentral v0.9.45 with an updated MeshCentral Assistant. I did a major fix, let me know if that works! Remote desktop should be smooth now. - Ylian

**Comment by VINISHVV** [comment]
@Ylianst - Thanks, But its still showing little hanging issues.
Can you check it once again?

**Comment by pggsadmin** [comment]
@Ylianst
I just upgraded the server to latest version. I can confirm that still assistant showing hanging issue.

**Comment by Ylianst** [comment]
I just published MeshCentral v0.9.46 with another fix. Not sure what "hanging issues" is, but fixed bug where incorrect portions of the screen are updated.

**Comment by Ylianst** [comment]
Seems like @SPEMoorthy indicated the latest fix worked. Waiting confirmation from others.

**Comment by VINISHVV** [comment]
@Ylianst 
Perfect fix.... This issue is resolved in MeshCentral v0.9.46.

**Comment by pggsadmin** [comment]
Thanks @Ylianst for this prefect fix.

**Comment by Ylianst** [comment]
Nice!!! Thanks for reporting back!
