### ISSUE TITLE
Keyboard accessibility is subpar

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#341]
- [x] On the login screen, there's no way to select the "Create One" link with the keyboard.
- [x] In the "Account Creation" form (after clicking the "Create One" link) pressing enter in the second password field should equate to clicking "Create Account".
- Once logged in, there are a number of things you can't do using the keyboard.
    - Switch between screens.
        - [x] Sections down left side.
        - [x] Subsections across top.
        - [x] Style selector at top right
    - [x] Open device group from My Devices section.
        (You can click on the name of the device group with mouse, but can't tab to it with keyboard.)
    - [x] Open single device from My Devices section.
    - [x] "Router" link on General - single-device subsection.
    - [x] Open device group from My Account section when devices in device group.
    - [ ] Open device group from My Account section when no devices in device group.
    - [x] View user from General - device-group subsection.
    - [x] Download events button.
    - [x] Open single user.
    - [x] Download Users button.
    - [x] Batch create users button.
    - [ ] When creating new device group, or editing existing device group, pressing enter while in name field should equate to clicking "OK".
    - [ ] In console screens, you can't use the keyboard to leave the console screen.

**Comment by Ylianst** [comment]
I am glad you reported this, I had to do some research on how to fix this and realized that I was not using <a ref onclick></a> correctly. Published MeshCentral v0.3.7-j with a fix for the 2 first points on the login screen. I will have to work on the main site quick a bit to fix everything.

**Comment by MailYouLater** [comment]
Got a chance to check this.  The fixes you've applied so far seem to be working.  I understand the main UI will take some time and effort to make keyboard accessible, but I'm glad to see that it is something you are concerned with, and I look forward to future improvements in this regard.

**Comment by Ylianst** [comment]
For "creating new device group, or editing existing device group", I was looking at fixing this, but the description box is multi-line and so, I am not sure pressing enter when in the name should press "OK". Instead, it should move to the next field?

![xx](https://user-images.githubusercontent.com/1319013/60835914-29729280-a179-11e9-88f1-e4be81142224.png)

**Comment by Ylianst** [comment]
I just fixed a lot of the links on the main web application so you could tab to them. Also, set the focus right after a dialog box show up. This will be in the next published version and going to be a lot of ongoing work.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.7-k with lots of changes for keyboard input. For example, the "Files" tab would not work at all before and it's now ok. I am going to have to go screen-by-screen and fix things.

**Comment by MailYouLater** [comment]
If you're in the Name field, and want to go to the Description field, you'd probably hit <kbd>Tab</kbd>, not <kbd>Enter</kbd>.  If you don't want to enter a description, or if the existing description is fine, and you only want to edit the name, I think you should be able to press <kbd>Enter</kbd> in the Name field to accept your changes.

**Comment by MailYouLater** [comment]
> I am going to have to go screen-by-screen and fix things.

If you edit the first post to have a list of screens, similar to the list I had to begin with, you can check them off as you go and easily see your progress.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.7-o with lots of keyboard improvements. If someone can verify that in the line above is working and what is not, that would be great. Thanks.

**Comment by MailYouLater** [comment]
> If someone can verify what in the list above is working and what is not, that would be great. Thanks.

Edited opening post.  Things are looking a lot better for keyboard accessibility.  Thanks Ylian.

**Comment by Ylianst** [comment]
Wow! Thanks for updating so quickly. I will take a look at the rest soon.

**Comment by Ylianst** [comment]
Just fixed "Open device group from My Devices section", will be in the next release.

**Comment by MailYouLater** [comment]
Feel free to check things off, and/or edit the post to add any more things that should be on there.

**Comment by Ylianst** [comment]
Next version of MeshCentral when I publish it should check off the last 3 boxes. I don't mind having you check them off, this way I know it works as expected :) Once done, if you can close this issue. You can then open a new one for more requests, that way we don't have issues that last forever and gets I "closed issues" score up!

**Comment by MailYouLater** [comment]
I'll take a look at those when you've uploaded the new version.  There's one more thing though:  
The tab order is different in different view modes.  In particular, the user interface selection diamond is before either of the top navigation bars in the top bar interface, and between the left and top navigation bars in top bar and fixed width interfaces.  I'm not necessarily sure where it should be in the tab order, but it should be consistent between all available views.  (Actually come to think of it, the tab order is un-intuitive in other areas too, but that should probably get its own issue later. After this one is solved.)

| Current tab orders |
| - |
| ![Left bar interface](https://user-images.githubusercontent.com/1279475/61234209-57128b00-a6e7-11e9-9143-5cc3595db572.png) |
| ![Top bar interface](https://user-images.githubusercontent.com/1279475/61234836-f1270300-a6e8-11e9-936e-3ff1c825cd94.png) |

**Comment by Ylianst** [comment]
Yes, this is good feedback. By the way, I published MeshCentral v0.3.7-u that should check all of the original boxes from the first post above. I will have to take a look at tab ordering.

**Comment by MailYouLater** [comment]
I can't get any of those three remaining items on the above list to work with either v0.3.7-u or v0.3.7-p, in Firefox, Chrome, Edge or Opera.

Tab order usually reflects the order elements appear in the HTML.

**Comment by MailYouLater** [comment]
Just updated to v0.3.7-y and that checks off one more box, but still can't hit enter to accept name change and can't leave console screens via keyboard because enter key is captured by console no matter where the keyboard focus is.

**Comment by MailYouLater** [comment]
Ah, I see what was going on with my last couple of comments.  I didn't think those recent versions should have changed anything regarding this issue.  So in the one where the device groups weren't working, I didn't have any devices in any of my groups, 'cause I just installed meshcentral, created an empty device group, and tried to tab to the name.  When it worked, it had a device in the group.

**Comment by dinger1986** [comment]
@si458 seems to be largely non issue this one
![image](https://github.com/Ylianst/MeshCentral/assets/7244447/af37889f-396f-45e3-aa77-786cbf43ae54)
is multiline so enter shouldnt work and console should capture all input, thats literally a personal preference
