### ISSUE TITLE
Peering is broken

### ISSUE THREAD

**Issue by rallisf1** [Ylianst/MeshCentral#5373]
**Describe the bug**
Peers cannot connect. Agents connected with 1 peer appear offline in the others.

**To Reproduce**
Setup peering as per https://www.youtube.com/watch?v=j8xIRGScju0
Same data folder and everything. For convenience I use mongodb Atlas. I will change to a local replica when it works.

**dubug -peer**
_server 1_
```
PEER: OutPeer s2: Connecting to: wss://ip.of.server.2:443/meshserver.ashx
PEER: OutPeer s2: Connected
PEER: OutPeer: BAD MESSAGE(A1)
PEER: OutPeer s2: Disconnected
```
_server 2_
```
PEER: InPeer: Connected (ip.of.server.1)
PEER: InPeer: Soft disconnect null (ip.of.server.1)
PEER: InPeer disconnect undefined (ip.of.server.1)
```

**Server Software (please complete the following information):**
 - OS: Ubuntu 22.04
 - Virtualization: Docker (official image)
 - Network: WAN, no proxy
 - Version: 1.1.11
 - Node: v18.17.1

**Additional context**
I tried commenting out the ["BAD MESSAGE" check](https://github.com/Ylianst/MeshCentral/blob/04a71800fa4ce94fb75ac480a4562498d17b8fbf/multiserver.js#L104) to see how far it will go but it errors again in the next statement on line 107 with `PEER: OutPeer: Server hash mismatch.`.

I then tried disabling TLS altogether and peering over ws:// but then errored out on line 130 with `PEER: OutPeer: Server sign check failed.`

Something is really wrong with the certificate comparison going on in multiserver.js

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "mongoDb": "mongodb+srv://username:password@mycluster.mongodb.net/?retryWrites=true&w=majority&replicaSet=atlas-dvh64d-shard-0",
    "MongoDbBulkOperations": true,
    "mongoDbChangeStream": true,
    "cert": "my.domain",
    "SessionKey": "SOME_SESSION_KEY",
    "WANonly": true,
    "port": 443,
    "redirPort": 80,
    "AgentPong": 300,
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": true,
  },
  "domains": {
    "": {
      "hide": 5,
      "newAccounts": false,
      "userNameIsEmail": true,
      "agentSelfGuestSharing": false
    },
    "my-second.domain": {
      "dns": "my-second.domain",
      "hide": 5,
      "newAccounts": false,
      "userNameIsEmail": true,
      "agentSelfGuestSharing": false
    }
  },
  "peers": {
    "serverId": "s1",
    "servers": {
      "s1": { "url": "wss://server.public.ip:443/" },
      "s2": { "url": "wss://server.public.ip:444/" }
    }
  }
}
```
In the second configuration file the only thing that changes is the `serverId` to `s2` and I use docker port mapping to map the second instance's ports to +1 (81,444,4434).

**Comment by si458** [comment]
Can you share your docker compose at all?

**Comment by rallisf1** [comment]
> Can you share your docker compose at all?

You're right, forgot that.

```yaml
version: '3'

networks:
  meshcentral-tier:
    driver: bridge

services:

  meshcentral:
    restart: always
    container_name: meshcentral
    image: ghcr.io/ylianst/meshcentral:latest
    ports:
      - 80:80
      - 443:443
      - 4433:4433
    env_file:
      - .env
    volumes:
      - ./data:/opt/meshcentral/meshcentral-data
      - ./meshcentral:/opt/meshcentral/meshcentral
      - ./debug.sh:/opt/meshcentral/startup.sh
    networks:
      - meshcentral-tier

  meshcentral:
    restart: always
    container_name: meshcentral
    image: ghcr.io/ylianst/meshcentral:latest
    ports:
      - 81:80
      - 441:443
      - 4434:4433
    env_file:
      - .env
    volumes:
      - ./data:/opt/meshcentral/meshcentral-data
      - ./meshcentral:/opt/meshcentral/meshcentral
      - ./debug2.sh:/opt/meshcentral/startup.sh
    networks:
      - meshcentral-tier
```

just added the debug argument in the start up script for s1  (debug.sh)
```sh
#!/bin/bash

if [ -f "meshcentral-data/${CONFIG_FILE}" ]; then
    node meshcentral/meshcentral --configfile "${CONFIG_FILE}" --debug peer
else
    cp config.json.template meshcentral-data/"${CONFIG_FILE}"
    if [ -n "$USE_MONGODB" ] && [ "$USE_MONGODB" == "true" ]; then
        if [ -z "$MONGO_URL" ]; then
            prefix=""
            if [ -n "$MONGO_INITDB_ROOT_USERNAME" ] && [ -n "$MONGO_INITDB_ROOT_PASSWORD" ]; then
                prefix="$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@"
            fi
            MONGO_URL="${prefix}mongodb:27017"
        fi
        sed -i "s/\"_mongoDb\": null/\"mongoDb\": \"mongodb:\/\/$MONGO_URL\"/" meshcentral-data/"${CONFIG_FILE}"
    fi
    sed -i "s/\"cert\": \"myserver.mydomain.com\"/\"cert\": \"$HOSTNAME\"/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"NewAccounts\": true/\"NewAccounts\": $ALLOW_NEW_ACCOUNTS/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"enabled\": false/\"enabled\": $ALLOWPLUGINS/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"localSessionRecording\": false/\"localSessionRecording\": $LOCALSESSIONRECORDING/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"minify\": true/\"minify\": $MINIFY/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"WebRTC\": false/\"WebRTC\": $WEBRTC/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"AllowFraming\": false/\"AllowFraming\": $IFRAME/" meshcentral-data/"${CONFIG_FILE}"
    if [ -z "$SESSION_KEY" ]; then
        SESSION_KEY="$(cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w 48 | head -n 1)"
    fi
    sed -i "s/\"_sessionKey\": \"MyReallySecretPassword1\"/\"sessionKey\": \"$SESSION_KEY\"/" meshcentral-data/"${CONFIG_FILE}"
    if [ "$REVERSE_PROXY" != "false" ]; then
        sed -i "s/\"_certUrl\": \"my\.reverse\.proxy\"/\"certUrl\": \"https:\/\/$REVERSE_PROXY:$REVERSE_PROXY_TLS_PORT\"/" meshcentral-data/"${CONFIG_FILE}"
        node meshcentral/meshcentral --configfile "${CONFIG_FILE}"
        exit
    fi
    node meshcentral/meshcentral --configfile "${CONFIG_FILE}" --cert "$HOSTNAME"
fi
```
and another one for the s2 config (debug2.sh)
```sh
#!/bin/bash

if [ -f "meshcentral-data/${CONFIG_FILE}" ]; then
    node meshcentral/meshcentral --configfile "/opt/meshcentral/meshcentral-data/config2.json" --debug peer
else
    cp config.json.template meshcentral-data/"${CONFIG_FILE}"
    if [ -n "$USE_MONGODB" ] && [ "$USE_MONGODB" == "true" ]; then
        if [ -z "$MONGO_URL" ]; then
            prefix=""
            if [ -n "$MONGO_INITDB_ROOT_USERNAME" ] && [ -n "$MONGO_INITDB_ROOT_PASSWORD" ]; then
                prefix="$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@"
            fi
            MONGO_URL="${prefix}mongodb:27017"
        fi
        sed -i "s/\"_mongoDb\": null/\"mongoDb\": \"mongodb:\/\/$MONGO_URL\"/" meshcentral-data/"${CONFIG_FILE}"
    fi
    sed -i "s/\"cert\": \"myserver.mydomain.com\"/\"cert\": \"$HOSTNAME\"/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"NewAccounts\": true/\"NewAccounts\": $ALLOW_NEW_ACCOUNTS/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"enabled\": false/\"enabled\": $ALLOWPLUGINS/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"localSessionRecording\": false/\"localSessionRecording\": $LOCALSESSIONRECORDING/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"minify\": true/\"minify\": $MINIFY/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"WebRTC\": false/\"WebRTC\": $WEBRTC/" meshcentral-data/"${CONFIG_FILE}"
    sed -i "s/\"AllowFraming\": false/\"AllowFraming\": $IFRAME/" meshcentral-data/"${CONFIG_FILE}"
    if [ -z "$SESSION_KEY" ]; then
        SESSION_KEY="$(cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w 48 | head -n 1)"
    fi
    sed -i "s/\"_sessionKey\": \"MyReallySecretPassword1\"/\"sessionKey\": \"$SESSION_KEY\"/" meshcentral-data/"${CONFIG_FILE}"
    if [ "$REVERSE_PROXY" != "false" ]; then
        sed -i "s/\"_certUrl\": \"my\.reverse\.proxy\"/\"certUrl\": \"https:\/\/$REVERSE_PROXY:$REVERSE_PROXY_TLS_PORT\"/" meshcentral-data/"${CONFIG_FILE}"
        node meshcentral/meshcentral --configfile "${CONFIG_FILE}"
        exit
    fi
    node meshcentral/meshcentral --configfile "${CONFIG_FILE}" --cert "$HOSTNAME"
fi
```

**Comment by si458** [comment]
done a PR so you dont have to edit the docker image next time for debug
you will be able to set an environment `ARGS=--debug peer` in the next release!

**Comment by si458** [comment]
i think you are using the same config file on each machine as both 'pods' are using the same value
` - ./data:/opt/meshcentral/meshcentral-data`

so they should be 
`- ./data1:/opt/meshcentral/meshcentral-data`
`- ./data2:/opt/meshcentral/meshcentral-data`

also you havent share ur `.env` file?

**Comment by rallisf1** [comment]
> i think you are using the same config file on each machine as both 'pods' are using the same value ` - ./data:/opt/meshcentral/meshcentral-data`

I change it via the startup script

> also you havent share ur `.env` file?

doesn't matter as I had a config file from the start but here you go

```
NODE_ENV=production

USE_MONGODB=true
# set already exist mongo connection string url here
#MONGO_URL=
# or set following init params for new mongodb, use it with docker-compose file with mongodb version
MONGO_INITDB_ROOT_USERNAME=username
MONGO_INITDB_ROOT_PASSWORD=password

# initial meshcentral-variables
# the following options are only used if no config.json exists in the data-folder

# your hostname
HOSTNAME=my.domain
# set to your reverse proxy IP if you want to put meshcentral behind a reverse proxy
REVERSE_PROXY=false
REVERSE_PROXY_TLS_PORT=
# set to true if you wish to enable iframe support
IFRAME=false
# set to false if you want disable self-service creation of new accounts besides the first (admin)
ALLOW_NEW_ACCOUNTS=false
# set to true to enable WebRTC - per documentation it is not officially released with meshcentral and currently experimental. Use with caution
WEBRTC=true
# set to true to allow plugins
ALLOWPLUGINS=false
# set to true to allow session recording
LOCALSESSIONRECORDING=false
# set to enable or disable minification of json, reduces traffic
MINIFY=false
```

**Comment by si458** [comment]
hmmm thanks ill have to have a look when i can, ive never tried peering before?

**Comment by si458** [comment]
just tried it here and it works fine no problems but i used a local mongodb rather than a cloud one
it took some time to setup (mainly mongodb)

docker-compose
```
version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    command: --replSet "rs0"
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081
  meshcentral1:
    image: ghcr.io/ylianst/meshcentral:latest
    ports:
      - 1234:443
    volumes:
      - data:/opt/meshcentral/meshcentral-data
      - user_files:/opt/meshcentral/meshcentral-files
      - backup:/opt/meshcentral/meshcentral-backups
      - web:/opt/meshcentral/meshcentral-web
    environment:
      - HOSTNAME=mc.mytest.com
      - CONFIG_FILE=config.json
  meshcentral2:
    image: ghcr.io/ylianst/meshcentral:latest
    ports:
      - 12345:443
    volumes:
      - data:/opt/meshcentral/meshcentral-data
      - user_files:/opt/meshcentral/meshcentral-files
      - backup:/opt/meshcentral/meshcentral-backups
      - web:/opt/meshcentral/meshcentral-web
    environment:
      - HOSTNAME=mc.mytest.com
      - CONFIG_FILE=config2.json
volumes:
  mongodb:
  data:
  user_files:
  backup:
  web:
```
make sure your STOP both meshcentrals after they start as you need to configure MONGO first

used this url to setup replicaset with just a single server rather than 3
https://www.mongodb.com/docs/manual/tutorial/deploy-replica-set/

i then used mongo-express to create the meshcentral database

config.json (config2.json is IDENTICAL apart from serverId is meshcentral2 rather than meshcentral1)
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "mongoDb": "mongodb://mongo:27017/meshcentral?replicaSet=rs0",
    "mongoDbChangeStream": true,
    "cert": "mc.mytest.com",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "QMCZ8LBNDL8HDQM27EYR85WWNCDOV4R1D1XAVC7ZA7AAS42H",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": false
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "minify": false,
      "NewAccounts": false,
      "localSessionRecording": false,
      "_userNameIsEmail": true,
      "_certUrl": "my.reverse.proxy"
    }
  },
  "peers": {
      "serverId": "meshcentral1",
      "servers": {
          "meshcentral1": {
              "url": "wss://meshcentral1:443/"
          },
          "meshcentral2": {
              "url": "wss://meshcentral2:443/"
          }
      }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }
}
```

start meshcentral1
setup user and create group
then start meshcentral2
go to url on meshcentral2 and works fine

**Comment by rallisf1** [comment]
are agents relayed though? did you add a device to meshcentral1 and open a connection (terminal/desktop/file) to it from meshcentral2 ?

**Comment by si458** [comment]
@rallisf1 ive just re-read ur first post ` Peers cannot connect. Agents connected with 1 peer appear offline in the others.`
i didnt try as i through the issue was trying to set it up! my bad! let me try wont be long

**Comment by rallisf1** [comment]
Ylianst does some magic comparison with the certificates, that goes way over my head, which seems broken. I've made my peace with it for now. If no other genius can fix it I could rewrite it but it won't be pretty and possibly less secure.

**Comment by si458** [comment]
i think the is an issue when the other server connects but then disconnects it as its showing wrong info?
![image](https://github.com/Ylianst/MeshCentral/assets/765314/88f7aa3b-1615-466b-98b5-affaf9009b61)

**Comment by rallisf1** [comment]
> EDIT: turns out docker created the meshcentral_network cuz of compose and used the 192.168.0.0/20 range? bugger know why?

It doesn't matter, it isn't a network issue. I've tried it with public servers and it does the same.

InPeer means the connection is incoming (aka you are seeing server 2 logs), the authentication takes place on the server creating the connection (OutPeer, server 1). The reason you see it connecting and disconnecting instantly is because the websocket connection is established (connected) but the once the authentication fails it disconnects and tries again a few moments later.

**Comment by si458** [comment]
MY DEBUG NOTES:
```
// Server authentication request
if (msg.length != 98) { obj.parent.parent.debug('peer', 'OutPeer: BAD MESSAGE(A1)'); return; }
```
so it doesnt like the length of the websocket message it receives?

**Comment by rallisf1** [comment]
Not just the length, the contents. But those are some sort of hash created from the server certificate. It should be the same, at least when sharing the same data folder, but it's not. I couldn't debug any further as my knowledge of SSL certificates is limited to creating and using them. Best thing I can do is replace the peering authentication method completely but I have no clue what problems that's gonna cause.

**Comment by Ylianst** [comment]
@rallisf1 Can you change line 104 of multiserver.js with the following line:

```
                            // Server authentication request
                            if (msg.length != 98) { obj.parent.parent.debug('peer', 'OutPeer: Bad server authentication message, length = ' + msg.length + ', should be 98. HEX: ' + Buffer.from(msg.substring(0, 4096), 'binary').toString('hex')); return; }
```

Then run again and see what you get. The hex info provided is no secret (hash or your cert and random number). i just checked in an update to this error.

**Comment by Ylianst** [comment]
I just did a possible fix for this. [Grab the latest multiserver.js here](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/multiserver.js), keep a backup of the old one. Replace and run again. Let me know if it works.

**Comment by rallisf1** [comment]
I'll test it out ASAP, posting from bed it's 1am here and Mondays are impossible. Will close this if we're good!

**Comment by Ylianst** [comment]
Thanks. Yes, close if it's good. If not, the new error messages will give me a hint as to what is going on.

**Comment by si458** [comment]
Hi @Ylianst the patch didnt work
my output says 
`OutPeer: Bad server authentication message, length = 81, should be 98. HEX: 0001135c3ffd343cfd0733061773fd7d7ffd547d241271655f7bfd7d1267fdfd2f2329bd39ce596c1865b8606ba8cf98c71e50f78e72a91720a5e0257f2969855ccd9c6115ad27527469b9e229ff30727a`

**Comment by Ylianst** [comment]
Interesting. I will look into it!

**Comment by Ylianst** [comment]
Found it! In "certoperations.js" replace:

```
    // Return the SHA384 hash of the certificate public key
    obj.getPublicKeyHashBinary = function (pem) {
        const { X509Certificate } = require('crypto');
        if (X509Certificate == null) {
            // This version of NodeJS (<v15.6.0) does not support X509 certs, use Node-Forge instead which only supports RSA certs.
            var publickey = obj.pki.certificateFromPem(pem).publicKey;
            return obj.pki.getPublicKeyFingerprint(publickey, { encoding: 'binary', md: obj.forge.md.sha384.create() });
        } else {
            // This version of NodeJS supports x509 certificates
            // TODO: THIS IS NOT CORRECT, this is SHA254 of the entire cert.
            return Buffer.from(new X509Certificate(pem).fingerprint256.split(':').join(''), 'hex');
        }
    };
```

With this:

```
    // Return the SHA384 hash of the certificate public key
    obj.getPublicKeyHashBinary = function (pem) {
        // This version of NodeJS (<v15.6.0) does not support X509 certs, use Node-Forge instead which only supports RSA certs.
        var publickey = obj.pki.certificateFromPem(pem).publicKey;
        return obj.pki.getPublicKeyFingerprint(publickey, { encoding: 'binary', md: obj.forge.md.sha384.create() });
    };
```

That will fix it. The problem is that new smaller function does not support ECDSA certs and I have to work on a fix for that. For most people that replacement is ok.

**Comment by Ylianst** [comment]
Ok, I have a real fix! Grab and replace to the latest [certoperations.js](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/certoperations.js) and it should work just fine. I am very impressed with that is possible in NodeJS 15.6 and higher. I will almost be able to completely remote ForgeJS as a dependency and fully support non-RSA certs.

**Comment by si458** [comment]
bingo @Ylianst thank fixed the issue!
is it normal for the certificates to be re-generated and the exes to be re-signed?

**Comment by Ylianst** [comment]
Thanks and no, it's not normal unless you change the name of your server or the certificate is invalid. If your seeing that all the time let me know.

**Comment by si458** [comment]
@Ylianst I found my issue with the cert signing over and over
It's because both servers in the peer are using the same data folder but different config files in the same data folder
And when one server starts up, it's code-signing the exes, but then when the other server starts up, it's then code-signing the exes again
Not sure if this is by design or a bug?
I'll open a separate issue for this

**Comment by Ylianst** [comment]
Ok. I run `node meshcentral --configfile config1.json` and `node meshcentral --configfile config2.json` to run my two servers in the same folder. I don't get that problem.

**Comment by KellyDi0te** [comment]
Hello, 

I tried to do the same, but replacing certoperations.js doesn't fix the bug for me. 
I have 3 peers, here are the logs I got : 

Server 1 to server 2 :
```
14:26:32 - PEER: OutPeer central2: Disconnected
14:26:32 - PEER: OutPeer: Server hash mismatch.
14:26:32 - PEER: OutPeer central2: Connected
14:26:32 - PEER: OutPeer central2: Connecting to: wss://ip_of_server2:443/meshserver.ashx
```

Server 1 to server 3 (I believe it's a MongoDB error because the service won't turn on) : 

```
14:28:39 - PEER: OutPeer central3: Disconnected
14:28:39 - PEER: OutPeer central3: Error: Error: connect ECONNREFUSED ip_of_server3:443
14:28:37 - PEER: OutPeer central3: Connecting to: wss://ip_of_server3:443/meshserver.ashx
```

Server 2 : 
``` 
14:29:52 - PEER: InPeer disconnect undefined (ip_of_server1)
14:29:52 - PEER: InPeer: Soft disconnect null (ip_of_server1)
14:29:52 - PEER: InPeer: Invalid signature.
14:29:52 - PEER: InPeer: Connected (ip_of_server1)
```

Server 3 : 
```
14:32:50 - PEER: InPeer disconnect undefined (ip_of_server1)
14:32:50 - PEER: InPeer: Soft disconnect null (ip_of_server1)
14:32:50 - PEER: InPeer: Invalid signature.
14:32:50 - PEER: InPeer: Connected (ip_of_server1)

14:32:58 - PEER: InPeer disconnect undefined (ip_of_server2)
14:32:58 - PEER: InPeer: Soft disconnect null (ip_of_server2)
14:32:58 - PEER: InPeer: Invalid signature.
14:32:58 - PEER: InPeer: Connected (ip_of_server2)
```

Thanks a lot for your help.

**Comment by rallisf1** [comment]
@KellyDi0te did you also replace mutliserver.js ? [higher in the thread there's an updated one.](https://github.com/Ylianst/MeshCentral/issues/5373#issuecomment-1732679678)

**Comment by KellyDi0te** [comment]
@rallisf1 : Yes i have also updated multiserver.js. 

By rebooting all the machines, i have now the message "BAD MESSAGE(A1)" on server 1 :

```
15:14:35 - PEER: OutPeer central2: Disconnected
15:14:35 - PEER: OutPeer: BAD MESSAGE(A1)
15:14:35 - PEER: OutPeer central2: Connected
15:14:35 - PEER: OutPeer central2: Connecting to: wss://ip_of_server2:443/meshserver.ashx
```

On server 2 and 3, I have : 
```
15:15:47 - PEER: InPeer disconnect undefined (ip_of_server1)
15:15:47 - PEER: InPeer: Soft disconnect null (ip_of_server1)
```

Thanks !

**Comment by KellyDi0te** [comment]
Hello again,

I updated my meshcentral servers from v1.1.10 to v1.1.15 and it's still not working.. 

On server 2 i have : 
```
PEER: InPeer: Connected (172.16.7.95)
Peer sign fail 2
PEER: InPeer: Invalid signature.
PEER: InPeer: Soft disconnect null (172.16.7.95)
PEER: InPeer disconnect undefined (172.16.7.95)
```

On server 1 I have : 
```
PEER: OutPeer central2: Connecting to: wss://VM-Mesh3.hdl.pri:443/meshserver.ashx
PEER: OutPeer central2: Connected
PEER: OutPeer: Server hash mismatch.
PEER: OutPeer central2: Disconnected
```

My config.json hasn't changed at all so I don't know what's going on @Ylianst ...

**Comment by si458** [comment]
is this still an issue with 1.1.27 ?

**Comment by KellyDi0te** [comment]
Hello,
I have no idea as we downgraded to a single standalone server...

Le jeu. 5 sept. 2024 à 14:07, Simon Smith ***@***.***> a
écrit :

**Comment by si458** [comment]
@KellyDi0te ok thats fine, i will close this issue then
but peering should be fixed now in 1.1.29 tho 👍

**Comment by KellyDi0te** [comment]
Ok i just did the tests by doing a brand new installation on 2 servers, 1.1.30 and 1.1.31 

Issue is still there with the exact same error messages :

Server 1 : 
```
PEER: OutPeer central2: Connecting to: wss://meshcentral1.hdl.pri:443/meshserver.ashx
PEER: OutPeer central2: Connected
PEER: OutPeer: Server hash mismatch.
PEER: OutPeer central2: Disconnected

```
Server 2 : 
```
PEER: InPeer: Connected (ip_of_meshcentral1)
Peer sign fail 2
PEER: InPeer: Invalid signature.
PEER: InPeer: Soft disconnect null (ip_of_meshcentral1)
PEER: InPeer disconnect undefined (ip_of_meshcentral1)
```

I'm beginning to think that it's an error of configuration from my side but i double checked everything....

**Comment by si458** [comment]
@KellyDi0te yes it does seem to be an issue with your setup possible
both config files should be identical APART from the peers section which has different names
and you should also make sure both meshcentral-data folders are identical too on each machine (apart from config.json)

**Comment by KellyDi0te** [comment]
Ok that's it, I just copied meshcentral-data from server 1 to server 2 and it worked.
Stupid mistake from my side!

**Comment by si458** [comment]
@KellyDi0te yeh no worries!
It's because the ssl certs have to match one another
Even tho u don't use them as u would use a load balancing reverse proxy to handle all the incoming external traffic to meshcentral :)
