### ISSUE TITLE
Bug: MC integrated MeshCommander: Unable to save mescripts (0.4.1-x)

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#553]
I noticed that the integrated MeshCommander's script editor is unable to save mescript files. MC itself (not a browser save as dialogue) asks for a filename and then nothing further happens.

Steps to reproduce:
1. open a AMT-enabled device in MC
2. open "Intel AMT" tab
3. click "Connect" button
4. wait for AMT to sync and select "Script Editor" item from menu on the left
5. click "Save..." button

Expected results:
A download of the .mescript is offered so depending of the browser's configuration either a browser save as dialogue pops up or the browser saves it directly to the Downloads folder (only for the last-mentioned, asking for a file name prior to offer it for download actually makes sense).

Actual results:
MC shows a website dialogue asking for a script file name, nothing further happens.

**Comment by Ylianst** [comment]
That is a bug, thanks for the report.

**Comment by Ylianst** [comment]
This was fixed a while back. Apologies for not reporting it. I will close this since I am pretty sure it's fixed, but feel free to re-open if needed.

**Comment by veitw** [comment]
Hi @Ylianst,

at least for MeshCentral 0.4.5-x in Firefox, this issue persists:

![grafik](https://user-images.githubusercontent.com/16285895/71074344-64dea780-2182-11ea-9ff4-e40a9f9cbac7.png)

This dialogue is the only interaction I get when pressing the "Save..." button in MeshCentral-embedded MeshCommander's script editor. Hitting "OK" simply closes the dialogue, there is neither a file selector dialogue following, nor appears the file anywhere in MeshCentral's My Files tab.

Best regards,
// Veit
