### ISSUE TITLE
Terminal encoding

### ISSUE THREAD

**Issue by ahdung** [Ylianst/MeshCentral#5600]
MeshCentral: 1.1.16
NodeJS: 14.17.1
Server OS: WIndows server 2012 R2 x64 chinese language, codepage:936
Client OS: WIndows 7 sp1 x64 chinese language, codepage:936

![微信截图_20231202125341](https://github.com/Ylianst/MeshCentral/assets/12094247/43eeddb9-5058-457e-b023-753189a2015c)

**Comment by bbrendon** [comment]
Pretty sure this is a duplicate
Duplicate https://github.com/Ylianst/MeshCentral/issues/4528 https://github.com/Ylianst/MeshCentral/issues/4435

**Comment by si458** [comment]
nice catch @bbrendon!
@ahdung check the output of the contpty in the console tab by running `osinfo`
also my post from last year i had this problem, but just tried it now and i dont have the issue anymore? weird? 
https://github.com/Ylianst/MeshCentral/issues/4435#issuecomment-1240965496

**Comment by ahdung** [comment]
@si458 My issue different, no Escape Code, just encoding incorrect. This is my `osinfo`:
![image](https://github.com/Ylianst/MeshCentral/assets/12094247/bdb0ef02-b502-488c-9173-ffa0f113a48e)

Text edition:
```
> osinfo
OS: Microsoft Windows 7 旗舰版  - 7601 [ConPTY: NO]
```

And `minify` not set(ignored), my `config.json`:
```json
{
   "settings": {
      "cert": "***",
      "WANonly": true,
      "port": ***,
      "redirPort": 0,
      "mpsPort": 0,
      "webRTC": true,
      "_tlsOffload": false,
      "_mpsTlsOffload": true,
      "_trustedProxy": "***",
      "_minify": true,
      "autoRemoveInactiveDevices": 1
   },
   "domains": {}
}
```

**Comment by RTechSn** [comment]
Still relevant.

**Comment by RTechSn** [comment]
I've checked this on the latest version and it's fixed now.

**Comment by ahdung** [comment]
@RTechSn Good news, I'll check it, thank you.

**Comment by ahdung** [comment]
@RTechSn I upgraded to the latest 1.1.48, issue still here.

<img width="813" height="353" alt="Image" src="https://github.com/user-attachments/assets/3c4017aa-7477-4af5-9de1-96086454d5e2" />
