### ISSUE TITLE
SSH Credentials not being remembered if username=email

### ISSUE THREAD

**Issue by tschettervictor** [Ylianst/MeshCentral#5833]
In version 1.1.21 I’m now running into a bug that will not let me save the ssh credentials of local devices if my username is a email address. They are being reset on every connection.

anyone else?

**Comment by tschettervictor** [comment]
I believe I have found a bug.

When setting up the server for the first time, before creating any users, I set the “usernameisEmail”: true variable
If I do that, the credentials don’t seem to be able to save, once logging in.

But if i just create a username normally without first setting that variable, then credentials save as they should.

**Comment by tschettervictor** [comment]
Im just wondering if there are any fixes planned for this. Otherwise I'll have to switch all my users to a normal username, which might be a slight headache.

**Comment by tschettervictor** [comment]
@si458 perhaps you can point me to the relevant file to sift through and see if I can spot anything that would cause this behaviour.

**Comment by si458** [comment]
this is weird? because i can see it goes to add the ssh creds into the db, but saves, but never actually saves?
just trying to work out why its not saving in the db

**Comment by si458** [comment]
ok seems to be a BUG with nedb, if i use mysql or sqlite, it works no problem

**Comment by si458** [comment]
ok BIG problem, nedb doesnt handle fullstops correctly, so this would require a huge change for nedb
https://github.com/seald/nedb/issues/55#issuecomment-1973309978

**Comment by si458** [comment]
ok so another work around is to remove the line below from inside `model.js` inside nedb package
```
  if (k.indexOf('.') !== -1) {
    throw new Error('Field names cannot contain a .');
  }
``` 
so we need to look at working out HOW to replace fulls with maybe something else? or base64 encode the email address?

**Comment by tschettervictor** [comment]
Will look at migrating to mongodb for now…

**Comment by tschettervictor** [comment]
> Will look at migrating to mongodb for now…

Unfortunately MongoDB does not really work properly on my FreeBSD server. But I will try MariaDB.

**Comment by si458** [comment]
you could try sqlite...
stop meshcentral, set `sqlite: true` under `settings` in config.json
Then run `node node_modules/meshcentral --nedbtodb`
This will convert the nedb to any DB u specify in your config.json
Then start meshcentral again

**Comment by tschettervictor** [comment]
Confirmed working as expected using MariaDB. Migration was as easy as 
1. `node node-modules/meshcentral --dbexport database.json`
2. configure a mariadb database and add mariadb json block to config.json
3. `node node-modules/meshcentral --dbimport database.json`

If you fix the NeDB, please let us know, but I believe MariaDB will serve better anyway.

**Comment by si458** [comment]
Glad u got it sorted!
only issue with dbexport is it doesn't export events as far as im aware, only the config

**Comment by tschettervictor** [comment]
Any plans to integrate another database as default?
NeDB is long EOL it seems.

**Comment by si458** [comment]
i did ask @Ylianst but at the moment we are leaving it as it is,
i personally think we could shift to sqlite as the default, but the size can get massive quickly

**Comment by Ylianst** [comment]
Ok, looking into this now.

**Comment by si458** [comment]
@Ylianst the issue as explained above here https://github.com/Ylianst/MeshCentral/issues/5833#issuecomment-1973315430
is because the json keys (names) contain fulls stops, so if the username is an email address, its not saving the value, 
its not the json values but the keys!

**Comment by Ylianst** [comment]
Ha yes, I just replicated the issue on my test server. In NeDB, I have to escape the "." on many of the fields due to how it works. I basically need to escape this case also. Hold on.

**Comment by Ylianst** [comment]
Just fixed it. Replace the file common.js with the [latest one here](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/common.js) and it will work.

**Comment by si458** [comment]
yep can confirm all works here! its encoding the string as `user/testing123/simon@mycompany%2Ecom`

**Comment by tschettervictor** [comment]
Hmmm. It doesn't seem to be working for me though.

**Comment by si458** [comment]
Did u replace the single file? And restart meshcentral? Ans switch bk to using nedb?

**Comment by tschettervictor** [comment]
> Did u replace the single file? And restart meshcentral? Ans switch bk to using nedb?

Yes i did. Basically removed the line for MariaDB, did a --dbimport, changed the file, and started the server again.

**Comment by tschettervictor** [comment]
Hang on just a sec. The issue I'm having is that my MeshCental username is my email. The credentials for the ssh and rdp connection themselves don't matter.

If my MeshCentral username is my email, then it doesn't work. Are we on the same page?

**Comment by si458** [comment]
@tschettervictor yes that's my setup, usernameisemail and it works OK here now, saving into nedb with the master common.js being replaced

**Comment by tschettervictor** [comment]
> @tschettervictor yes that's my setup, usernameisemail and it works OK here now, saving into nedb with the master common.js being replaced

Ok thanks. But its still not working for me. Tried different connections but no go

**Comment by si458** [comment]
can you share ur config.json please? (hide secret info)

**Comment by tschettervictor** [comment]
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "mesh.domain.com",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "string",
    "sessionTime": 168,
    "port": 8443,
    "_debug": true,
    "aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "TlsOffload": "192.168.50.135",
    "_trustedProxy": "192.168.50.135",
    "_MariaDB": {
      "_host": "localhost",
      "_user": "meshcentral",
      "_password": "password",
      "_database": "meshcentral"
    }
  },
  "domains": {
    "": {
      "title": "domain",
      "title2": "domain",
      "certUrl": "https://192.168.50.135",
      "ssh": true,
      "mstsc": true,
      "_minify": true,
      "_newAccounts": true,
      "allowsavingdevicecredentials": true,
      "userNameIsEmail": true,
      "agentInviteCodes": true
    }
  },
  "smtp": {
    "host": "smtp.gmail.com",
    "port": "465",
    "from": "HBCoR Management",
    "user": "email",
    "pass": "password",
    "tls": true
  }
}

```

**Comment by Ylianst** [comment]
To make sure, when accessing SSH to save credentials, your using this option?

![image](https://github.com/Ylianst/MeshCentral/assets/1319013/98c4179f-9c90-4aa2-99f7-3b16067f2adc)

**Comment by tschettervictor** [comment]
> To make sure, when accessing SSH to save credentials, your using this option? In the screenshot, you can see it's an email username and I was able to save credentials.
> 
> ![image](https://private-user-images.githubusercontent.com/1319013/309604838-98c4179f-9c90-4aa2-99f7-3b16067f2adc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTg1ODAsIm5iZiI6MTcwOTUxODI4MCwicGF0aCI6Ii8xMzE5MDEzLzMwOTYwNDgzOC05OGM0MTc5Zi05YzkwLTRhYTItOTlmNy0zYjE2MDY3ZjJhZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMDIxMTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmNmOTI2NTJmMTQwNTllYzRlODQxODE3MmFkZTA3NzY5NGE4OGY4YTE3NjU3YzY3Yjg4YmMyN2FiMmNkYTY3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vgfy1m0DP7FdJjCjbFSCUCCyYk3gxRauyNEM92-zJb0)

Yes. I also use Terminal, SSH Connect and that also doesn't work.

**Comment by tschettervictor** [comment]
It does show the credentials as saved on the device page, but it still asks for a login when clicking connect.

**Comment by tschettervictor** [comment]
And I can't clear the credentials either.

**Comment by tschettervictor** [comment]
> And I can't clear the credentials either.

The fix seems to allow saving credentials that have "." in them. But my issue is that when my MeshCentral username has periods in it or is an email, then I can't save credentials. When I log in as a user without periods in it, I can save them properly. @Ylianst

**Comment by tschettervictor** [comment]
It looks like this bug is back in version 1.1.22

I am using mariadb as my database this time, but its again not letting me save the SSH credentials.
@si458

**Comment by tschettervictor** [comment]
> It looks like this bug is back in version 1.1.22
> 
> I am using mariadb as my database this time, but its again not letting me save the SSH credentials. @si458

Meanwhile, back on version 1.1.21 everything works again.

**Comment by si458** [comment]
@tschettervictor This has been fixed recently in PR #6001 so you just need to wait for a new release or npm install from git repo or use docker master image

**Comment by tschettervictor** [comment]
> @tschettervictor This has been fixed recently in PR #6001 so you just need to wait for a new release or npm install from git repo or use docker master image

Ok. I assumed it was part of 1.1.22

**Comment by si458** [comment]
It was fixed but then something else broke in 1.1.22 #5994

**Comment by tschettervictor** [comment]
Any update on this? I could check it again unless you think it’s still broken.

**Comment by si458** [comment]
Just released 1.1.15 give it a try, if still not working, we will have to investigate more, maybe u can give access to ur machine for us to debug?

**Comment by tschettervictor** [comment]
Ok will update here.

**Comment by si458** [comment]
You might also have to clear ur ssh credentials if it thinks they are saved, and resave them

**Comment by tschettervictor** [comment]
Looks fixed in 1.1.25 at least.

Tested on a fresh installation. Password and key files are now being saved even if my meshcentral username is an email address.

Thanks.

**Comment by si458** [comment]
@tschettervictor glad it's resolved on a fresh install anyways! Maybe try updating ur main machine and see if its fixed there?
It might be you have to delete the entry from the database on ur main machine to get it working again!
