### ISSUE TITLE
Machine desktop switch shows previous connection

### ISSUE THREAD

**Issue by lleal99B** [Ylianst/MeshCentral#6388]
**Describe the bug**
I didn't use versions 1.1.25 to 1.1.29, I'm not sure when it began.

When a machine desktop is active and goes back to the computer list, selects another computer and select remote it shows the desktop of the previous machine. Must click disconnect and connect to show the right desktop.

**To Reproduce**
1. Start with an active desktop connection
2. Click on the back arrow to the computer list
3. Select another machine
4. Click desktop
5. Shows the previous machine active desktop but with the label of the new selected computer.

**Expected behavior**
When the user has an active desktop connection, and selects another computer and clicks on "Desktop" the page must show the connection options of the selected computer, no the desktop of the previous computer.

**Screenshots**

![image](https://github.com/user-attachments/assets/b9c8c2a8-cf6a-4ef2-acd8-30bb78debd2d)

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: None
 - Network: WAN, Traefik
 - Version: 1.1.29
 - Node: 12.22.9 and 20.17.0

**Client Device (please complete the following information):**
 - Device: PC, Laptop, VM (Others)
 - OS: Windows
 - Network: LAN and WAN
 - Browser: Chorme, Edge Brave
 - MeshCentralRouter Version: No

**Comment by si458** [comment]
Duplicate of https://github.com/Ylianst/MeshCentral/issues/6382

Has already been fixed

Will be in next release or u can use the master docker image or the development build or patch it yourself!

**Comment by lleal99B** [comment]
Hi Simon,

 

My fault, I didn’t check closed issues. Sorry.

 

Best regards,

 

Luis

**Comment by si458** [comment]
No worries!
It was my mistake.
I fixed one bug and then created another 🤦‍♂️

**Comment by smartekIT** [comment]
> No worries! It was my mistake. I fixed one bug and then created another 🤦‍♂️

Hi @si458 , the bug still there in version 1.30 but slightly different. now if you are connected to a desktop and you loose your internet connection. when you try to view the desktop it only shows black screen. trying to soft disconnect the agent then it still showing black screen only even though it says connected. So to get around that have to restart the meshcentral service on meshcentral server.

I have broswer ping, bong enabled with value 50
I also have agent ping, pong enabled with value 50
I have use webrtc false

what could be the issue here? didn't have that on version 1.24 which I upgraded from to 1.30.

Thanks

**Comment by si458** [comment]
@smartekIT please open up a seperate issue for your issue (keeping things tidy 👍 )
the change i did was remove the line that always disconnected ur sessions
because it was effecting users who was logged in when groups changed via ldap https://github.com/Ylianst/MeshCentral/issues/6240

**Comment by smartekIT** [comment]
sorry @si458 for this but I thought it might be related. next time I will for sure. By any chance can you refer to the exact line your removed so I can revert it and see if it fixes my issue? Thanks

**Comment by si458** [comment]
@smartekIT this was the original fix https://github.com/Ylianst/MeshCentral/issues/6240#issuecomment-2308918182
then this was the fix afterwards as it kept the sessions opened by mistake https://github.com/Ylianst/MeshCentral/issues/6382#issuecomment-2349383932
