### ISSUE TITLE
The "Clipboard" pull/push text support lang

### ISSUE THREAD

**Issue by GusevVictor** [Ylianst/MeshCentral#817]
Dear all, when I use the "Clipboard" button to pull/push text into the remote clipboard I can't send any lang except English.

I will glad if you can fix that.

![изображение](https://user-images.githubusercontent.com/7081357/72223925-47380e80-3585-11ea-8adb-ee1e445fe89b.png)

notepad in remote site:

![изображение](https://user-images.githubusercontent.com/7081357/72223941-6d5dae80-3585-11ea-80ec-dde4784bfc68.png)

**Comment by Ylianst** [comment]
Oh, this is clearly a bug. Good report.

**Comment by GusevVictor** [comment]
I hope you will fix that. I have many other bug I can create report. I'm not a programmer just sysadmin :( I think you are God with @krayon007!

**Comment by krayon007** [comment]
Does this not work when the target machine is windows, Linux, or both?

**Comment by GusevVictor** [comment]
> 
> 
> Does this not work when the target machine is windows, Linux, or both?

Hi. In all cases I can't use it with my native lang. The linux console does not support any other lang at all... #816  I cry.  Will be glad if you fix it. 

Best regard. 
Viktor.

**Comment by krayon007** [comment]
Interesting. I tried it with Chinese characters on remote desktop on windows and linux, and it seems to work correctly on Linux but not windows.

However, I see it doesn't work for either  for terminal, but I think I'll need to consult ylian on the latter, because I think the webpage dialog for terminal is not sending the characters correctly. I'll see if I can test Russian directly just in case.

**Comment by krayon007** [comment]
Ok, I fixed the clipboard on Windows, so it can copy/paste non-english on KVM. Tested with both Russian and Chinese... (This always worked on Linux KVM for me)

I also fixed the web app so that you can type/paste non-english characters on the terminal. I forwarded my server changes to @Ylianst , so he'll need to review/test it further, but all this should be fixed in an upcoming update... Most likely when he returns from his travels.

**Comment by GusevVictor** [comment]
**You are brilliant.** I will glad to test and feedback about your fix with new release! 

There is also problem in notification screeen I can create another report for that if need.

**Step to reproduce:**

Open remote Windows desktop from Windows client (Firefox)

Click on:
![изображение](https://user-images.githubusercontent.com/7081357/72411122-47016400-377b-11ea-91f7-2ff0f37e5bb5.png)

Input a text like this one:

![изображение](https://user-images.githubusercontent.com/7081357/72411159-597b9d80-377b-11ea-867d-eaae1f7fa913.png)

See the result:
![изображение](https://user-images.githubusercontent.com/7081357/72411185-67c9b980-377b-11ea-8f68-7981d6fcc928.png)

**Comment by GusevVictor** [comment]
> 
> 
> Ok, I fixed the clipboard on Windows, so it can copy/paste non-english on KVM. Tested with both Russian and Chinese... (This always worked on Linux KVM for me)
> 
> I also fixed the web app so that you can type/paste non-english characters on the terminal. I forwarded my server changes to @Ylianst , so he'll need to review/test it further, but all this should be fixed in an upcoming update... Most likely when he returns from his travels.

Not working. The problem still here. Windows Clt (Firefox), Windows remote side.

v 0.4.7-L

Please, please fix.

**Comment by krayon007** [comment]
The clipboard pasting non-english characters into Windows KVM requires an agent update. We haven't pushed that agent update yet, but will soon...

**Comment by GusevVictor** [comment]
> 
> 
> The clipboard pasting non-english characters into Windows KVM requires an agent update. We haven't pushed that agent update yet, but will soon...

Notify in Russian now WORKS! :)

**Comment by GusevVictor** [comment]
0.4.7-s clipboard WORKS in Russian too! THANK. You are BRILLIANT!
