### ISSUE TITLE
List Expansion Broken for Tags with Spaces

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#878]
When I am in My Devices, Sort by Tags, all tags that are a single word the ^ allows me to expand the list or collapse the list under that tag.  But any tag with a space in the name that function is broken.  The little sideways carrot just does nothing for those.  Makes for a very long list.

**Comment by Ylianst** [comment]
Thanks for the report. Fixed in MeshCentral v0.4.8-a, let me know if it works.

**Comment by scottalanmiller** [comment]
Updated, refreshed the browser, but still seeing the issue (at least on Chrome.)

**Comment by Ylianst** [comment]
Humm... weird. I saw the same problem on my side and fixed it (FireFox and Chrome). Make sure your running the latest version then open the browser console and when you click to expand/collapse, do you see an error? If so, send it over - Thanks.

**Comment by scottalanmiller** [comment]
Oh, I should add, it happens ONLY in the LIST view, not in columns or desktops view.  But I can confirm that it does happen on Firefox, too.

**Comment by scottalanmiller** [comment]
I get nothing in the browser console when I try to collapse a section.  But when the page opens I get this...

NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface] network-response-listener.js:84

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-d with a fix. The problem that was it did not work in list mode, should work now.

**Comment by scottalanmiller** [comment]
All fixed now, thanks!
